export const sombra = "0px 4px 16px rgba(1, 28, 64, 0.2)";
export const fonteInter = "'Inter', sans-serif";
export const fonteOpen = "'Open Sans'";
export const corFonteCabecalho = "#212121";
export const corBackgroundBotao = "#48D0B0";
// export const = "";
// export const = "";
// export const = "";
// export const = "";